version: "3.3"
services:
  report_generator.server:
    build: .
    ports:
      - "8081:80"
    environment:
    - FACTORIES=4
    restart: always
    deploy:
      resources:
        limits:
          memory: 2048M